version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.5
    - 8.2.6
    - 8.2.7
    - 8.2.9
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.9.0
  - dependency-name: eslint
    versions:
    - 7.20.0
    - 7.21.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: autoprefixer
    versions:
    - 10.2.3
    - 10.2.4
    - 10.2.5
  - dependency-name: minify
    versions:
    - 7.0.0
    - 7.0.1
